// Generated by CoffeeScript 1.10.0
(function() {
  var __build__, gulp, swallowError, uglify;

  __build__ = "build";

  gulp = require("gulp");

  uglify = require("gulp-uglify");

  swallowError = function(error) {
    console.log(error.toString());
    return this.emit("end");
  };

  gulp.task("js", function() {
    return gulp.src(["webug.js"]).pipe(uglify()).pipe(gulp.dest(__build__ + "/"));
  });

  gulp.task("default", ["js"]);

}).call(this);

//# sourceMappingURL=gulpfile.js.map
