// Generated by CoffeeScript 1.10.0
(function() {
  (function(win, doc) {
    "user strict";
    var Stack, Webug, webug;
    Stack = (function() {
      function Stack() {
        this.data = [];
        this.index = 0;
      }

      Stack.prototype.push = function(msg) {
        this.data.push(msg);
        return this.index = this.data.length - 1;
      };

      Stack.prototype.up = function() {
        if (this.index !== 0) {
          return this.data[--this.index];
        } else {
          return this.data[this.index];
        }
      };

      Stack.prototype.down = function() {
        if (this.index !== (this.data.length - 1)) {
          return this.data[++this.index];
        } else {
          return this.data[this.index];
        }
      };

      return Stack;

    })();
    Webug = (function() {
      var CHANGE, CLICK, ERROR, HTML, INPUT, KEYDOWN, STYLE, TRUE, UNDEFINED, bind, dom, enumerable, enumerableAndNotEnumerable, getAttrs, getBody, getPropertyName, isArray, isNull, isNumber, isObejct, notEnumerable, unbind;

      STYLE = '.webug-container { position: fixed; bottom: 0; left: 0; width: 100%; height: 200px; font-color: #000; font-size: 16px; margin: 5px; padding: 5px; border-top: 3px solid #eeefee; overflow-y: scroll; } .webug-command { padding: 5px 0; } .webug-command::before { content: ">"; color: rgb(53, 131, 252); font-weight: bold; display: inline-block; margin-right: 5px; } .webug-information { margin: 0; padding: 0; } .webug-echo { font-size: 16px; padding: 5px 0; border-bottom: 1px solid #eeefee; list-style: none; } .webug-echo::before { content: ">"; color: rgb(133, 149, 173); font-weight: bold; display: inline-block; margin-right: 5px; } .webug-true { font-color: #066; border-bottom: 1px solid #eeefee; padding: 5px 12px; list-style: none; } .webug-error { color: #E81D20; border-bottom: 1px solid #eeefee; padding: 5px 12px; list-style: none; } .webug-error::before { content: "error: "; } .webug-edit { width: 80%; font-size: 16px; border: none; outline: none; } .webug-tips { position: fixed; right: 80px; bottom: 190px; border: 1px solid #000; } .webug-clear { position: fixed; bottom: 10px; right: 10px; padding: 2px 5px; }';

      HTML = '<div id="webug-container" class="webug-container"> <ul id="webug-content" class="webug-information"> </ul> <div class="webug-command"> <input id="webug-input" class="webug-edit"/> </div> <select id="webug-select" class="webug-tips"> </select> <button id="webug-btn-clear" class="webug-clear">Clear</button> </div>';

      UNDEFINED = void 0;

      CLICK = 'click';

      KEYDOWN = 'keydown';

      TRUE = 'true';

      ERROR = 'error';

      INPUT = 'input';

      CHANGE = 'change';

      dom = function(ele) {
        return doc.querySelector(ele);
      };

      bind = function(ele, event, callback) {
        return ele.addEventListener(event, callback, false);
      };

      unbind = function(ele, event, callback) {
        return ele.removeEventListener(event, callback, false);
      };

      isNull = function(val) {
        return val === null;
      };

      isArray = Array.isArray;

      isNumber = function(val) {
        return !isNaN(val);
      };

      isObejct = function(val) {
        return typeof val === "object" && !isArray(val) && !isNull(val);
      };

      getBody = function() {
        return doc.body || dom("body") || dom("html");
      };

      getAttrs = function(obj) {
        var attr, tmp;
        if (!isObejct(obj)) {
          return [];
        } else {
          attr = [];
          for (tmp in obj) {
            attr.push(tmp);
          }
          console.log(obj);
          return attr;
        }
      };

      enumerable = function(obj, prop) {
        return obj.propertyIsEnumerable(prop);
      };

      notEnumerable = function(obj, prop) {
        return !obj.propertyIsEnumerable(prop);
      };

      enumerableAndNotEnumerable = function() {
        return true;
      };

      getPropertyName = function(obj, iterateSelfBool, iteratePrototypeBool, includePropCb) {
        var i, len, prop, props, ref;
        props = [];
        while ((!!obj) === true) {
          if (iterateSelfBool === true) {
            ref = Object.getOwnPropertyNames(obj);
            for (i = 0, len = ref.length; i < len; i++) {
              prop = ref[i];
              if (prop.indexOf(prop === -1 && includePropCb(obj, prop))) {
                props.push(prop);
              }
            }
          }
          if (iteratePrototypeBool === false) {
            break;
          }
          iterateSelfBool = true;
          obj = Object.getPrototypeOf(obj);
        }
        return props;
      };

      Webug.prototype.render = function(msg, console) {
        var data, error, error1;
        if (msg === '') {
          return [TRUE, ''];
        } else {
          if (console == null) {
            this.append('echo', msg);
          }
          try {
            data = eval.call(win, msg);
            return [TRUE, isObejct(data) ? data.toString() : data];
          } catch (error1) {
            error = error1;
            return [ERROR, error];
          }
        }
      };

      Webug.prototype.handleObject = function() {};

      Webug.prototype.append = function(trueOrErr, value) {
        var li;
        li = doc.createElement('li');
        li.setAttribute('class', 'webug-' + trueOrErr);
        li.innerHTML = value;
        this.content.appendChild(li);
        return this.scrollBottom();
      };

      Webug.prototype.clear = function() {
        return this.content.innerHTML = '';
      };

      Webug.prototype.show = function() {
        this.isHide = false;
        this.container.setAttribute('style', 'display: block');
        return this;
      };

      Webug.prototype.hide = function() {
        this.isHide = true;
        this.container.setAttribute('style', 'display: none');
        return this;
      };

      Webug.prototype.searchAttribute = function(val, env) {
        var array, attrs, i, key, len;
        array = [];
        attrs = getPropertyName(env, true, true, enumerableAndNotEnumerable());
        for (i = 0, len = attrs.length; i < len; i++) {
          key = attrs[i];
          if (key.indexOf(val) === 0) {
            array.push(key);
          }
        }
        return array;
      };

      Webug.prototype.appendInSelect = function(array) {
        var all, i, len, size, tmp;
        all = '';
        for (i = 0, len = array.length; i < len; i++) {
          tmp = array[i];
          all += '<option>' + tmp + '</option>';
        }
        this.select.innerHTML = all;
        if (array.length > 8) {
          size = 8;
        } else {
          size = array.length + 1;
        }
        return this.select.setAttribute('size', size);
      };

      Webug.prototype.clearSelect = function() {
        return this.select.innerHTML = '';
      };

      Webug.prototype.inputListner = function(e) {
        var env, pos, tmp, val;
        val = this.input.value;
        pos = val.lastIndexOf('.');
        if (pos === -1) {
          env = win;
          this.env = '';
        } else {
          tmp = val.substring(0, pos);
          this.env = tmp + '.';
          env = eval(tmp);
        }
        val = val.substring(pos + 1, val.length);
        return this.appendInSelect(this.searchAttribute(val, env));
      };

      Webug.prototype.errListener = function(error) {
        var msg;
        return msg = ["Error:", "filename: " + error.filename, "lineno: " + error.lineno, "message: " + error.message, "type: " + error.type];
      };

      Webug.prototype.scrollBottom = function() {
        return this.container.scrollTop = this.container.scrollHeight;
      };

      function Webug() {
        this.isInit = false;
        this.msg = '';
        this.body = getBody();
        this.stack = new Stack();
        this.init();
        this.isInit = true;
      }

      Webug.prototype.init = function() {
        var css, div;
        this.isHide = false;
        this.env = '';
        css = doc.createElement('style');
        css.innerHTML = STYLE;
        div = doc.createElement('div');
        div.innerHTML = HTML;
        this.body.appendChild(css);
        this.body.appendChild(div);
        this.btn = dom("#webug-btn-clear");
        this.input = dom("#webug-input");
        this.content = dom('#webug-content');
        this.container = dom('#webug-container');
        this.select = dom('#webug-select');
        bind(this.btn, CLICK, (function(_this) {
          return function() {
            return _this.clear();
          };
        })(this));
        bind(this.input, KEYDOWN, (function(_this) {
          return function(e) {
            var data;
            if (e.keyCode === 13) {
              _this.msg = _this.input.value;
              _this.stack.push(_this.msg);
              data = _this.render(_this.msg);
              _this.append(data[0], data[1]);
              return _this.input.value = '';
            } else if (e.keyCode === 38) {
              return _this.select.focus();
            } else if (e.keyCode === 40) {
              return _this.select.focus();
            }
          };
        })(this));
        bind(this.input, INPUT, (function(_this) {
          return function(e) {
            return _this.inputListner(e);
          };
        })(this));
        bind(this.select, KEYDOWN, (function(_this) {
          return function(e) {
            if (e.keyCode === 13) {
              _this.input.value = _this.env + _this.select.value;
              _this.input.focus();
              return _this.clearSelect();
            } else if (e.keyCode === 37) {
              _this.input.focus();
              return e.preventDefault();
            }
          };
        })(this));
        bind(this.select, CLICK, (function(_this) {
          return function(e) {
            _this.input.value = _this.select.value;
            return _this.input.focus();
          };
        })(this));
        bind(this.body, KEYDOWN, (function(_this) {
          return function(e) {
            if (e.keyCode === 88 && e.ctrlKey) {
              if (_this.isHide) {
                return _this.show();
              } else {
                return _this.hide();
              }
            }
          };
        })(this));
        bind(win, ERROR, (function(_this) {
          return function(e) {
            return _this.errListener(e);
          };
        })(this));
        win.console.log = (function(_this) {
          return function(val) {
            var data;
            data = _this.render(val, true);
            _this.append(data[0], data[1]);
            return UNDEFINED;
          };
        })(this);
        this.isInit = true;
        return this;
      };

      return Webug;

    })();
    return webug = new Webug();
  })(window, document);

}).call(this);

//# sourceMappingURL=webug.js.map
